### ISSUE TITLE
cant obfuscate

### ISSUE THREAD

**Issue by lRoberth** [jkusner/LuaObfuscator#1]
C:\Users\rober>C:\Python34\python.exe C:\Users\rober\Desktop\LuaObfuscator-master\__main__.py [--input input.lua] [--output output.lua] [--level 1] [--dontcopy] [--debug]
Version: Beta 1.0.3 (Updated on Jun 09, 2016 @ 06:44 AM)
usage: __main__.py [-h] [--input INPUT] [--output OUTPUT] [--level LEVEL]
                   [--dontcopy] [--debug]
__main__.py: error: unrecognized arguments: [--input input.lua] [--output output.lua] [--level 1] [--dontcopy] [--debug]

**Comment by jkusner** [comment]
You are using the arguments wrong, you need to delete the [brackets] and use the parameters you need.

Example:

`C:\Python34\python.exe C:\Users\rober\Desktop\LuaObfuscator-master_main_.py --input input.lua --output output.lua --level 2 --dontcopy`

Will obfuscate a file named input.lua in the current directory, and save the obfuscated file as output.lua

**Comment by lRoberth** [comment]
> Microsoft Windows [Version 10.0.16299.309]
> (c) 2017 Microsoft Corporation. All rights reserved.
> 
> f:\Program Files\VCG\MeshLab>E:\Python34\python.exe E:\Python34\obfuscator\__main__.py --input init.lua --output output.lua --level 2 --dontcopy
> Version: Beta 1.0.3 (Updated on Jun 09, 2016 @ 06:44 AM)
> Fatal error occurred.

nope :p

**Comment by lRoberth** [comment]
never mind, got it working by my own, had to dig iinto the code and change where the files were loading
