### ISSUE TITLE
code Security, but not SIZE!

### ISSUE THREAD

**Issue by SupinePandora43** [jkusner/LuaObfuscator#10]
wikipedia about "Obfuscate" - make ureadeable and decrease size!

but [LuaObfuscator](https://github.com/jkusner/LuaObfuscator) only increase file SIZE!!!

[file with 1xx lines](https://github.com/SupinePandora43/Pandora-addon/blob/master/lua/autorun/pandoras_addon_main.lua) - size 4 KB

Lvl  | size
-----|----------------------------------------------------------------------------
-1 | 4 KB (not obfuscated)
0 | 10 KB
1 | 15 KB
2 | 11 KB
3 | 87 KB

**Comment by NoSharp** [comment]
This is a non issue.
