### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by peno1** [jkusner/LuaObfuscator#4]
So I am getting an error when trying to use this script on a linux(centos 7) system. It works perfectly fine on my windows pc, does this not work for linux systems because this is the error I get when I try to run it on linux:

`Traceback (most recent call last):
  File "__main__.py", line 2, in <module>
    import obfuscator
  File "/home/obfuscator.py", line 3, in <module>
    import tokenizer
  File "/home/tokenizer.py", line 139
    print("Fatal error occurred.", "Please check that your input is syntactically correct.", sep="\n")
                                                                                                ^
SyntaxError: invalid syntax
`

**Comment by jkusner** [comment]
Make sure you have the right Python version running, 3.4.3+
